image: "maven:3-jdk-8"

variables:
  PROJECT_DIR: "${CI_PROJECT_DIR}/4-Qualisicherung/project/vipr"

stages:
  - test
  - package

compile:
  stage: test
  script:
    - cd ${PROJECT_DIR} && mvn -q compile

jar:
  stage: package
  script:
    - cd ${PROJECT_DIR} && mvn -q package
  artifacts:
    name: "Executable JAR for $CI_COMMIT_REF_NAME"
    paths:
      - ${PROJECT_DIR}/target/vipr-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    when: always
    expire_in: 2 weeks

#checkstyle:
  # stage: test
   #script: 
  # - cd ${PROJECT_DIR} && mvn validate

spotbugs:
  script:
  - cd ${PROJECT_DIR} && mvn install -B
  - cd ${PROJECT_DIR} && mvn spotbugs:check

   
jacoco:
  stage: test
  script: 
   - cd ${PROJECT_DIR} && mvn install -B
   - cd ${PROJECT_DIR} && cat target/site/jacoco/index.html
   
pmd:
  stage: test
  script:
  - cd ${PROJECT_DIR} && mvn pmd:check
